### ISSUE TITLE
Customize the Google+ button

### ISSUE THREAD

**Issue by isaacfi** [abacritt/angularx-social-login#521] opened 2022-06-21 18:30 UTC
Hi,

I want to customize the Google+ login button, is there any way to do it? or how to click programmatically over "asl-google-signin-button" button? I tried this with no luck:

In html:
```
<asl-google-signin-button #googleButton [hidden]="true"></asl-google-signin-button>
        <button type="button" class="btn google-btn ml-auto" (click)="submitGoogleLogin()"><i
            class="fab fa-google-plus-g"></i> {{'loginWithGoogle' | translate}}</button>
```
In the TS:
```
@ViewChild('googleButton', { static: false}) googleButton: ElementRef;

submitGoogleLogin() {
    this.googleButton.nativeElement.click();
}
```

**Comment by Jin-K** [comment] 2022-06-27 14:26
Hi @isaacfi 

There are possibilities to customize the Google button through the [gis client](https://developers.google.com/identity/oauth2/web).
But they are very limited: https://developers.google.com/identity/gsi/web/guides/personalized-button.
And there is no click handler in `<asl-google-signin-button></asl-google-signin-button>`, it just wraps a button rendered by the gis client, which also wraps an IFrame.

The `<asl-google-signin-button></asl-google-signin-button>` is not supporting customization, it's more like a temporary way to delegate the button rendering (though gis client) to this project.

If you really want to try Google button customization with the gis client, you should do something like [this](https://github.com/abacritt/angularx-social-login/blob/f134053ad92bb61c283b5cd6e3d458fe33554adb/projects/lib/src/directives/google-signin-button.directive.ts#L15-L18) yourself. And you need to wait for [SocialAuthService.initState](https://github.com/abacritt/angularx-social-login/blob/f134053ad92bb61c283b5cd6e3d458fe33554adb/projects/lib/src/directives/google-signin-button.directive.ts#L14) first emit.

I think we're currently working on an alternative provider for Google, the current one is tricky, and we have almost no control on it as it delegates almost everything to the Google lib.
We should maybe add more warnings about this in the project README.

Otherwise, you can also implement your own login provider if you implement `LoginProvider` and/or extend `BaseLoginProvider`.
It became easier since [version 1.2.1](https://github.com/abacritt/angularx-social-login/commit/a421701abd2644763f7fe2d15cb767daee84fd88).
I have a custom login provider [here](https://github.com/Jin-K/azama-box/blob/main/projects/jin-k/google-oidc-login-provider/src/lib/google-oidc-login-provider.service.ts) which works for my needs, but it depends on angular-oauth2-oidc.

**Comment by rahulkutah** [comment] 2022-06-29 07:27
@Jin-K  as you have suggested I have created a custom provider, and it is working, but the dialog is not closing after sign in. Also how i can the information from the URL after sign in

**Comment by Heatmanofurioso** [comment] 2022-07-29 08:58
Closing as duplicate of #534

**Closed by Heatmanofurioso** 2022-07-29 08:58 UTC
