### ISSUE TITLE
Providers autologin users on Initialization

### ISSUE THREAD

**Issue by laertispappas** [abacritt/angularx-social-login#150] opened 2018-12-16 20:51 UTC
Hello, I'm using this library in an ng6 app, in order to provide SSO functionality. 

The way that I'm using it now is that in a login component I subscribe to `authstate` of `AuthService` instance to get the authenticated user. 

```
# file /some/path/login.component.ts
...
ngOnInit {
      this.socialAuthService.authState.subscribe((socialUser: SocialUser) => {
      if (socialUser) {
        this.store.dispatch(
          new auth.OAuthLoginAction(new OAuthUser(socialUser))
        );
      }
    });
}
``` 

The problem is that when a user is logged out and he tries to navigate to a protected resource, he is redirected to login component. From the above code and the way the providers are [implemented in the library](https://github.com/abacritt/angularx-social-login/blob/0c0e962ca5dd60a7b241390758c056e065b386dc/src/lib/src/auth.service.ts#L109) it will try to get the login status for a user and emit the next `_authState` to the subscribers on the component initialisation thus providing a kind of auto-login feature. 

From the action dispatched above an http request will be made to the API to authorize the user token in the backend and on success it will respond with a custom auth token that the backend generates in order for the client to send it on any future request so we identify the auth status of the user.

This is problematic in my scenario since I want the event to be emitted only when the user hits login with google and not to try to auto-login the user without requested. Moreover the above will emit for every provider unnecessarily events that no ones has requested which makes me think that there is a design smell here.

I'm not a front end guy, I work mostly in the backend so maybe my implementation is wrong but I would like to have your feedback on this issue that I'm facing and how to bypass it. 

thank you in advance.

Update: I removed the subscription on the initialization of the component and use `#signIn` to get the user instead from the resolved promise instead of subscribing to `authState`. My comment regarding the constructor though I think it is still valid. Why do we need to make the request on the service construction? 

```
 private oAuthSignIn(provderID: string) {
    this.socialAuthAervice.signIn(provderID).then(
      (socialUser: SocialUser) => {
        if (socialUser) {
          this.store.dispatch(
            new auth.OAuthLoginAction(new OAuthUser(socialUser))
          );
        }
      },
      err => console.log(`***** ${err} ****`)
    );
  }
```

**Comment by laertispappas** [comment] 2018-12-18 16:41
Update: I removed the subscription on the initialization of the component and use signIn directly to get the user instead

```
 private oAuthSignIn(provderID: string) {
    // this.socialAuthAervice.authState.subscribe((socialUser: SocialUser) => {
    //   if (socialUser) {
    //     this.store.dispatch(
    //       new auth.OAuthLoginAction(new OAuthUser(socialUser))
    //     );
    //   }
    // });

    this.socialAuthAervice.signIn(provderID).then(
      (socialUser: SocialUser) => {
        if (socialUser) {
          this.store.dispatch(
            new auth.OAuthLoginAction(new OAuthUser(socialUser))
          );
        }
      },
      err => console.log(`***** ${err} ****`)
    );
  }
```

**Comment by chrstphrrbn** [comment] 2018-12-22 21:02
I have the same problem, would you mind sharing your solution?

**Comment by jaibatrik** [comment] 2018-12-26 15:30
Are you using the `signOut` method provided by the library to logout the user? In that case, the `socialUser` should be null.

**Comment by laertispappas** [comment] 2018-12-28 10:04
@jaibatrik  yes I do use the `signOut` but I don't think this is relevant with what I described above.

**Comment by jaibatrik** [comment] 2018-12-28 16:05
> The problem is that when a user is logged out and he tries to navigate to a protected resource...

If the user was logged out using the `signOut` method, the auto-login will fail and `null` will be emitted to the subscribers.

May be I am missing some other part of your question.

**Comment by laertispappas** [comment] 2019-01-07 14:52
@jaibatrik  thanks for the update. 

As described I was subscribing on the initialization of the Login component to `authState`.  I don't know if this is correct or wrong. The side effect on this is that even if you log out, when I was visiting Login page again I was auto signing in with each provider. 

I changed the implementation to not subscribe in `authState` on the login component initialization but instead call `signIn` ad hoc on demand (when the user actually clicks sign in with G). This solves my issue. I just wanted to address the issue from design perspective and get a feedback about my implementation. 

Please feel free to close the issue.

**Comment by nagendragillalu** [comment] 2019-01-09 06:07
Hi,

Even I was facing same issue,but passing revoke flag as "true" to signOut method worked for me.

`   signOut(): void {
    this.authService.signOut(true);
  }`

Now I am not auto logged in.

**Comment by dfmorillov** [comment] 2019-10-02 14:59
I'm having a similar problem. I am working with angular 4 social login and I have the authService service in two components. The problem is when the implementation of one of the components is also called the service that is in the other component. How do I get the services called only in the component that I need.

**Comment by raykin** [comment] 2019-10-03 04:33
```
signOut(): void { this.authService.signOut(true); }
```
does not work in my code.  SignOut can't remove credential even I follow the design described in laertispappas's comment.

**Comment by zaid4kspr** [comment] 2020-05-01 12:14
i think you can make a  clickLogin = false; then when you user click login via google or facebook make it  this.clickLogin = true
and  when subscribe test so if he didn't click the button yet nothing will happen 
    this.authService.authState.subscribe((user) => {
      if (this.clickLogin) {
        this.loginViaSocial(user) // call you back-end api
      }
    }, catcherror => this.catcherror = true
    );

**Comment by jaibatrik** [comment] 2020-05-09 16:39
I'll be closing this issue for now. I think the auto-login is the intended behavior for most of the scenarios. We can revisit this if more issues come up.

**Closed by jaibatrik** 2020-05-09 16:39 UTC
