### ISSUE TITLE
How can i get token expiry date?

### ISSUE THREAD

**Issue by vishal8802** [abacritt/angularx-social-login#293] opened 2020-07-13 10:27 UTC

**Comment by jaibatrik** [comment] 2020-07-13 14:06
I guess, we have to enhance the `SocialUser` class a bit to address these issue. I'll try to take care of this shortly.

**Comment by afgonzal** [comment] 2020-07-13 14:59
there´s already another thread here
[https://github.com/abacritt/angularx-social-login/issues/274](https://github.com/abacritt/angularx-social-login/issues/274)
with the solution

**Comment by jaibatrik** [comment] 2020-07-14 11:40
duplicate of #274

**Comment by jaibatrik** [comment] 2020-07-14 11:40
Duplicate of #274

**Closed** 2020-07-26 10:53 UTC
