### ISSUE TITLE
Refused to display 'https://www.facebook.com/home.php' in a frame because it set 'X-Frame-Options' to 'deny'

### ISSUE THREAD

**Issue by Pratikshakhandagale** [abacritt/angularx-social-login#225] opened 2019-10-31 10:33 UTC
Facing this issue while logout from facebook login. Did not found any solution for this.

**Comment by somcoder** [comment] 2019-10-31 19:19
Possible duplicate of #151.
Probably not a problem with this library, [this](https://stackoverflow.com/questions/22331373/facebook-js-api-cant-logout) may help.

**Comment by Pratikshakhandagale** [comment] 2019-11-01 10:44
> Possible duplicate of #151.
> Probably not a problem with this library, [this](https://stackoverflow.com/questions/22331373/facebook-js-api-cant-logout) may help.

@somcoder - Thanks for reply.
Above solution work for me.

**Closed** 2019-11-01 10:45 UTC
