### ISSUE TITLE
LinkedIn Login not working when I am integrating it with my application.

### ISSUE THREAD

**Issue by AchintMaheshwari** [abacritt/angularx-social-login#79] opened 2018-04-25 10:37 UTC
![image](https://user-images.githubusercontent.com/38721943/39240803-7a231ae6-48a2-11e8-8ece-5d7a14de7ead.png)
This is the error I am getting when I am integrating the social login for linkedin.
Kindly help me on this.

**Comment by devotebest** [comment] 2018-05-30 01:20
@AchintMaheshwari 
I got same error.
Do you find solution?
Thanks

**Comment by devotebest** [comment] 2018-06-07 06:47
@AchintMaheshwari 
Do you have any good news?
Looking forward to your hearing.
Thanks

**Comment by isaleem** [comment] 2018-06-09 01:32
Added a comment on https://github.com/abacritt/angularx-social-login/issues/97, can you confirm if it helps.

**Comment by jaibatrik** [comment] 2018-06-18 10:32
Duplicate of #97

**Closed by jaibatrik** 2018-06-18 10:32 UTC
Labels: bug
