### ISSUE TITLE
PWA integration

### ISSUE THREAD

**Issue by afriedma** [abacritt/angularx-social-login#130] opened 2018-09-07 14:51 UTC
Hi,

Sorry I am using an issue tracking for the question.  But I am wondering if you tested the functionality with progressive web apps and if not, do you think it can be integrated with pwa?

Thank you,

Alex

**Comment by jaibatrik** [comment] 2018-11-25 04:40
Duplicate of #6.

**Closed by jaibatrik** 2018-11-25 04:40 UTC
