### ISSUE TITLE
Unable to signout

### ISSUE THREAD

**Issue by rrubio** [abacritt/angularx-social-login#13] opened 2017-09-29 02:16 UTC
Hi Guys,

I manage to login ok, however, when trying to logout i get the following error:

Using the following to signout: 

`  signOut(): void {
    this.authService.signOut();
  }
`

`core.es5.js:1020 ERROR Error: Uncaught (in promise): Login provider not found
    at resolvePromise (zone.js:783)
    at zone.js:709
    at ng4-social-login.umd.js:88
    at new ZoneAwarePromise (zone.js:847)
    at AuthService.webpackJsonp.../../../../ng4-social-login/ng4-social-login.umd.js.AuthService.signOut (ng4-social-login.umd.js:75)`

**Comment by jaibatrik** [comment] 2017-10-03 15:52
Can you provide a system where I can observe the issue? May be create a small project and upload in github?

**Comment by rrubio** [comment] 2017-10-04 12:26
@jaibatrik thanks for getting back to me. I'll try setting one up this week and let you know.

**Comment by vinayak114** [comment] 2017-10-30 11:33
Please give any solution for this issue.Thanks

**Comment by evan-boissonnot** [comment] 2017-10-30 13:59
Hello 

I've got the same issue today.
I have just followed your tutorial to install the module.

And when I want to logout, it seems to be ok.
And, when I refresh the page, i'm yet connected.

**Comment by jaibatrik** [comment] 2017-10-31 06:01
Are you guys getting any error in JavaScript console? Do you have any page where I can see the issue?

**Comment by vinayak114** [comment] 2017-10-31 12:58
It is not signing out from google when we use this method signOut(): void { this.authService.signOut(); }

**Comment by vinayak114** [comment] 2017-11-02 11:05
Can Anybody Tell what is this Login Provider It is giving this error

**Comment by damilolasodiq** [comment] 2017-11-20 22:09
Hello,
I get `Error: Uncaught (in promise): TypeError: Cannot read property 'provider' of null` any time I try to signOut

`this._socialAuthService.signIn(FacebookLoginProvider.PROVIDER_ID).then(() => {
            this._socialAuthService.authState.subscribe((user) => {
                console.log(user);
                this._socialAuthService.signOut();
                //this.googleAuth.unsubscribe();
            });
        })`

**Comment by ninianh** [comment] 2017-11-22 09:56
Hello,
I have same issue. Are you guys managed to address this issue, or have any workaround. Please share it.
Currently, on console, it is showing not-related/helpful error (Refused to display 'https://www.facebook.com/home.php' in a frame because it set 'X-Frame-Options' to 'deny'.)

**Comment by nirali-ga** [comment] 2017-12-11 06:17
Follow the last answer steps of this question......it will get solved
[(https://stackoverflow.com/questions/37652221/facebook-login-cant-load-url-the-domain-of-this-url-isnt-included-in-the-app)]

**Comment by nehil** [comment] 2017-12-28 06:05
Facebook logout not working.
It fails to log out sometimes or either log out of facebook as well.

**Comment by ninianh** [comment] 2018-04-11 01:36
Here is my steps to make it(logout) work

1. Go to facebook dev app => Settings => Basic
2. Fill mysite to app domains and Site URL fields. Ex: mysite.com and https://mysite.com
3. Click Save, now the logout works

Please note: it works only on my domain, not localhost

**Comment by jaibatrik** [comment] 2018-05-03 05:28
Looks like the issue is with app configuration in Facebook Developer site. Closing this.

**Closed by jaibatrik** 2018-05-03 05:28 UTC

**Comment by agnaveen** [comment] 2018-05-19 08:19
I understood that signout for fb wont work properly in localhost. Any other way to test this in local or any other configuration need to be done in fb settings ?

**Comment by rahulswimmer** [comment] 2018-07-07 07:33
I used Google authentication using [npm-6-social-login](https://www.npmjs.com/package/angular-6-social-login). Sign in working as expcted and it is generating a token as well. Using the same instance, i called the signOut method, but it doesn't logs you out of google. Please refer the link and let me know of any possibilities for logout.

**Comment by faridaanjum** [comment] 2018-09-07 06:58
@jaibatrik I am using angularx-social-login for facebook login..

In my app this.authService.signOut(); is not working, the user remains same in the authstate, it is not becoming null. If I logout from the facebook and again clicking on the signin using facebook , without entering facebook details it is taking the previous user details and opening my app. after that the facebook login page is displaying .. what is the problem i am not getting. could you please help me in this. If it is the problem with app configuration please tell me the details.

Thanks in advance

**Comment by rahulswimmer** [comment] 2018-09-09 17:55
Ouath just makes the Google instance null, hence it  you out of Google. Now
that's how the architecture is made. Logging out of Google, if you Logout
of your app is a dirty work, but can't help if the requirement stipulates
the same. Hence add the following to your signOut() function. My project
was an Angular 6 app:

document.location.href = "
https://www.google.com/accounts/Logout?continue=https://appengine.google.com/_ah/logout?continue=http://localhost:4200
";

Here localhost:4200 is the URL of my app. If your login page is xyz.com
then input that.

**Comment by namanjainsmtgroup** [comment] 2020-04-20 06:07
Hi, 

Please use this 
signOut(): void { this.authService.signOut(true); }

**Comment by niraz100** [comment] 2020-05-23 20:20
if you guys still suffering from this issue this code may help you its work for me

facebookUser;
  signOut() {
    this.authService.authState.subscribe((user) => {
      this.facebookUser = user;
      if (this.facebookUser) {
        this.fbsignOut();
      }
    });
}
fbsignOut(): void {
    this.authService.signOut(true);
    return;
  }

**Comment by naordah69** [comment] 2023-05-11 09:37
Had the same issue
In my case i mistakingly loaded socialLoginModule inside lazy loaded module
And the config at the app module

Moving both of them to app.module solved my issue
