### ISSUE TITLE
Using library with Firefox

### ISSUE THREAD

**Issue by fzucaro** [abacritt/angularx-social-login#476] opened 2022-03-04 17:10 UTC
I have problem to use social login with Google on Firefox. It works fine in Chrome, Edge and Safari, but in firefox seems that after google authentication in popup, the angular application doesn't receive user logged.
I user libary version: 3.5.7 with angular 9 and firefox version is 97.01

**Comment by Heatmanofurioso** [comment] 2022-05-23 11:57
Hi @fzucaro 
The lib has changed quite a bit since that version.

Can you provide us with some info on the issue?
Any errors in the console when the issue occurs?

**Comment by Heatmanofurioso** [comment] 2022-06-19 19:59
Hey. `@abacritt/angularx-social-login:1.2.0` has been deployed.

Google Authentication should be fixed.
Follow up on https://github.com/abacritt/angularx-social-login/issues/489 for more info, since this is a duplicate of that issue

**Closed by Heatmanofurioso** 2022-06-19 19:59 UTC
