### ISSUE TITLE
I got this type of error.

### ISSUE THREAD

**Issue by BsiSuresh** [abacritt/angularx-social-login#329] opened 2020-10-14 06:29 UTC
I'm using angular 9. If i click social login button, i got this type of error.

''
![Screenshot from 2020-10-14 11-58-29](https://user-images.githubusercontent.com/70131554/95951766-9eb92280-0e14-11eb-9263-ed96eab520fe.png)

**Comment by jaibatrik** [comment] 2020-10-24 15:20
Duplicate of #280.

**Closed by jaibatrik** 2020-10-24 15:20 UTC
Labels: bug
