### ISSUE TITLE
Google login not workin on Chrome incognito mode

### ISSUE THREAD

**Issue by sebrojas14** [abacritt/angularx-social-login#487] opened 2022-04-01 01:37 UTC
I'm getting this always on Incogmnito (private) mode on Chrome:
```
core.mjs:6485 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'signIn')
TypeError: Cannot read properties of undefined (reading 'signIn')
    at :4200/vendor.js:18927:51
    at new ZoneAwarePromise (:4200/polyfills.js:4528:29)
    at GoogleLoginProvider.signIn (:4200/vendor.js:18925:12)
    at :4200/vendor.js:19118:26
...
```

**Comment by DydjyZ** [comment] 2022-04-06 00:41
I have the same error.
Moreover, I have this error before the above error : 

angularx-social-login.js:214 
details: "Cookies are not enabled in current environment."
error: "idpiframe_initialization_failed"

**Comment by beldenge** [comment] 2022-04-07 20:21
If you want it to work in incognito mode, I suggest you toggle off "Block third-party cookies" on the initial incognito landing screen.

**Comment by Heatmanofurioso** [comment] 2022-05-23 11:04
Hi @sebrojas14 
Was Beldenge's answer sufficient for you?

**Comment by Heatmanofurioso** [comment] 2022-05-23 11:16
This issue seems to also be a duplicated of what's being discussed in #292

**Comment by Heatmanofurioso** [comment] 2022-06-19 19:49
Closing as a duplicate of #292

**Closed by Heatmanofurioso** 2022-06-19 19:49 UTC
