### ISSUE TITLE
<asl-google-signin-button> css properties cannot be overwritten

### ISSUE THREAD

**Issue by northrain04** [abacritt/angularx-social-login#721] opened 2023-07-26 10:28 UTC
I am trying to understand how to change  the appereance of the Google SignIn button, but with the provided properties (like type, width, text,...) I cannot customize it enough to fit my application needs.

I suggest to expand the style properties that can be overridden and/or also put a method to call the sign in methods via code and not by clicking it.

If there is something that escapes me on that matter, any suggestion is welcome!

**Comment by egssalih** [comment] 2023-08-29 12:52
This is a real concern; I hope it will be addressed. Tried clicking it virtually it doesn't work since it is loading iFrame

**Comment by lwestfall** [comment] 2024-01-01 16:31
There's really not much that can be done here, google locks these buttons down hard. [See my response to a similar issue](https://github.com/abacritt/angularx-social-login/issues/744#issuecomment-1873387930) and [a SO explanation more pertinent to your complaint](https://stackoverflow.com/a/41061076/6621862)

**Comment by Heatmanofurioso** [comment] 2024-01-02 13:13
Thanks for your answer @lwestfall 
Closing this as a duplicate of https://github.com/abacritt/angularx-social-login/issues/744 and leaving that one open, as I'll probably be adding your example to the readme, so people can see up to where can we customize it.

**Closed by Heatmanofurioso** 2024-01-02 13:13 UTC
