### ISSUE TITLE
authState not returning data when the page is reloaded and you are signed out FB

### ISSUE THREAD

**Issue by Hangtu** [abacritt/angularx-social-login#160] opened 2019-01-28 22:28 UTC
If I call fbLogin() and later signOut() and later fbStateClick() method the console.log return 'false'.
but if I reload the page and I call fbStateClick() the authState does not return any data.

```
 fbLogin() {
     this.authService.signIn(FacebookLoginProvider.PROVIDER_ID);
  } 

signOut(): void {
    this.authService.signOut();
 }
fbStateClick() { 
this.authService.authState.subscribe((data) => {
      console.log(data);
      console.log((data != null) ? 'true' : 'false');
    }, err => console.log(err));
  }
}
```

**Comment by jaibatrik** [comment] 2019-01-30 15:50
Duplicate of #154. Reopen if I am wrong.

**Closed by jaibatrik** 2019-01-30 15:50 UTC
