### ISSUE TITLE
{"error":"popup_closed_by_user"}

### ISSUE THREAD

**Issue by DailisLangovskis** [abacritt/angularx-social-login#504] opened 2022-05-23 20:17 UTC
Hello, I was trying to use google sign in after the last patch, (Thank You for that as well), but now I stumbled on this error: `{"error":"popup_closed_by_user"}`, comes of [code_line](https://github.com/abacritt/angularx-social-login/blob/master/projects/lib/src/providers/google-login-provider.ts#L118)
I tried clearing all my Chrome and Firefox browser cache, as mentioned if few forums, but no luck. Anyone else is now experiencing this?

**Comment by AyuDiego** [comment] 2022-05-24 12:43
Same here, facebook login perfect but when i try to call service whit these provider the same error :/. And i try to clear coockies and all i saw but nothing works

**Comment by oliverfrost** [comment] 2022-05-25 09:45
I tried to implement everything from scratch using only Google`s JS API library and got the same error. So basically **@abacritt/angularx-social-login** has nothing to do with it.

There is a thread with lots of suggestions how to fix the problem but none of them worked for me:
https://stackoverflow.com/questions/48683320/google-sso-login-error-popup-closed-by-user

The only workaround I found so far is to use redirect instead of opening Google`s login screen in a separate window:

```typescript
 providers: [{
            id: GoogleLoginProvider.PROVIDER_ID,
            provider: new GoogleLoginProvider(
              'clientId',
              {
                  scope: 'email',
                  ux_mode: 'redirect'
              }
            )
          }]
```

And then extract 'id_token' from query parameters in url.

**Comment by veeravetrivel** [comment] 2022-05-26 07:34
Same for me too. Any improvement or how to be solved?

**Comment by theophane-girard** [comment] 2022-05-31 17:51
any news ? :)

**Comment by davidmr163** [comment] 2022-05-31 23:18
Hey, I found a solution that worked for me. 
Inside **app.module.ts** you have to add the following code in your _providers:_
```
providers: [
        {
          id: GoogleLoginProvider.PROVIDER_ID,
          provider: new GoogleLoginProvider(
            'clientId', {
              scope: 'email',
              plugin_name: 'login-app'
            }),
        }
      ], 
      onError: (err: any) => {
        console.error(err);
      },
    } as SocialAuthServiceConfig,
  },
  ],
```
where **plugin_name** must be the name you provided for your project in the google oauth api.

Hope this can help someone in need :)

**Comment by kartik1430** [comment] 2022-06-01 04:25
> Hello, I was trying to use google sign in after the last patch, (Thank You for that as well), but now I stumbled on this error: `{"error":"popup_closed_by_user"}`, comes of [code_line](https://github.com/abacritt/angularx-social-login/blob/master/projects/lib/src/providers/google-login-provider.ts#L118) I tried clearing all my Chrome and Firefox browser cache, as mentioned if few forums, but no luck. Anyone else is now experiencing this?

same problem..Did anyone resolve this ?

**Comment by franlaraa** [comment] 2022-06-01 08:46
> Hey, I found a solution that worked for me. Inside **app.module.ts** you have to add the following code in your _providers:_
> 
> ```
> providers: [
>         {
>           id: GoogleLoginProvider.PROVIDER_ID,
>           provider: new GoogleLoginProvider(
>             'clientId', {
>               scope: 'email',
>               plugin_name: 'login-app'
>             }),
>         }
>       ], 
>       onError: (err: any) => {
>         console.error(err);
>       },
>     } as SocialAuthServiceConfig,
>   },
>   ],
> ```
> 
> where **plugin_name** must be the name you provided for your project in the google oauth api.
> 
> Hope this can help someone in need :)

This worked for me,Thanks!

**Comment by pradosh05** [comment] 2022-06-06 17:17
> Hey, I found a solution that worked for me. Inside **app.module.ts** you have to add the following code in your _providers:_
> 
> ```
> providers: [
>         {
>           id: GoogleLoginProvider.PROVIDER_ID,
>           provider: new GoogleLoginProvider(
>             'clientId', {
>               scope: 'email',
>               plugin_name: 'login-app'
>             }),
>         }
>       ], 
>       onError: (err: any) => {
>         console.error(err);
>       },
>     } as SocialAuthServiceConfig,
>   },
>   ],
> ```
> 
> where **plugin_name** must be the name you provided for your project in the google oauth api.
> 
> Hope this can help someone in need :)

Thank you so much, Its working for me too @davidmr163

**Comment by veeravetrivel** [comment] 2022-06-08 06:07
But this error {"error":"popup_closed_by_user"} occurs rarely for some of the google users account. Cant able to solve this permanently.

**Comment by jviaches** [comment] 2022-06-09 04:46
Worked for me as well, huge thanks !

**Comment by Heatmanofurioso** [comment] 2022-06-13 08:22
This issue is being addressed in https://github.com/abacritt/angularx-social-login/pull/507

**Comment by Heatmanofurioso** [comment] 2022-06-13 08:32
I'm closing this issue so this gets discussed in a single thread, also since the other one is the oldest and the most active thread on this whole discussion.

The thread is in https://github.com/abacritt/angularx-social-login/issues/489

And the current PR in which we're trying to address the issue is https://github.com/abacritt/angularx-social-login/pull/507

**Closed by Heatmanofurioso** 2022-06-13 08:32 UTC

**Comment by jayna456** [comment] 2023-08-11 09:55
@davidmr163, by passing the second parameter, I am getting Expected 1 arguments, but got 2. Can you help me in this?

**Comment by jayna456** [comment] 2023-08-11 10:03
> I tried to implement everything from scratch using only Google`s JS API library and got the same error. So basically **@abacritt/angularx-social-login** has nothing to do with it.
> 
> There is a thread with lots of suggestions how to fix the problem but none of them worked for me: https://stackoverflow.com/questions/48683320/google-sso-login-error-popup-closed-by-user
> 
> The only workaround I found so far is to use redirect instead of opening Google`s login screen in a separate window:
> 
> ```ts
>  providers: [{
>             id: GoogleLoginProvider.PROVIDER_ID,
>             provider: new GoogleLoginProvider(
>               'clientId',
>               {
>                   scope: 'email',
>                   ux_mode: 'redirect'
>               }
>             )
>           }]
> ```
> 
> And then extract 'id_token' from query parameters in url.

By applying second parameter, I am getting **Expected 1 arguments, but got 2.**

Please help me out!
