### ISSUE TITLE
LoginOpt interface is not accessible

### ISSUE THREAD

**Issue by iamSathishMohan** [abacritt/angularx-social-login#61] opened 2018-02-20 12:25 UTC
![image](https://user-images.githubusercontent.com/22076855/36423807-4363588a-1667-11e8-818a-c6d47a77d81c.png)

**Comment by Gnorro** [comment] 2018-02-21 13:08
Yes, same problem

Thanks for fixing

**Comment by vgogov** [comment] 2018-02-21 14:25
It's all good, I just don't think the author @jaibatrik pushed it yet to NPM. Since on npm its v 1.1.1 while the latest version on GitHub is 1.1.4. Once the latest package is pushed, should all work :+1:

**Comment by jaibatrik** [comment] 2018-02-28 14:26
Fixed and pushed to github, will push to npm shortly.

**Comment by jaibatrik** [comment] 2018-02-28 14:26
Duplicate of #63

**Comment by jaibatrik** [comment] 2018-02-28 14:27
Pushed to npm as well.

**Closed by jaibatrik** 2018-02-28 14:26 UTC
