### ISSUE TITLE
Null user when logged in on first subscription

### ISSUE THREAD

**Issue by DouglasForst** [abacritt/angularx-social-login#81] opened 2018-05-04 23:31 UTC
When subscribing to authState I'm always getting a null user the first publish and then immediately followed by the real user. As a result I can't use this in an AuthGuard. In the example the user is written to the console twice (see image). Is this expected or am I doing something wrong?

`    public authState$: Observable<SocialUser> = this.authService.authState.pipe(
        map((user: SocialUser) => {
            console.log('user', user);
            return user;
        })
    );` 

<img width="847" alt="screen shot 2018-05-04 at 6 27 43 pm" src="https://user-images.githubusercontent.com/38991048/39656927-2c740e58-4fc9-11e8-8e20-3ebfdbfaf08e.png">

**Comment by lianyi** [comment] 2018-05-05 01:28
I have the same issue where the user was null then followed by real user.

**Comment by bergiusj** [comment] 2018-05-09 05:56
I have the exact same problem but after calling the signOut() method. After calling it and then directly calling signIn method on a button I get user null. If i click the button again the user is there. Any possible solutions on that?

**Comment by lianyi** [comment] 2018-05-10 02:36
@bergiusj I'm not sure that's the same cause but I found the solution for the **null user => then valid user** issue when user is logged in.  will send in a PR .

**Comment by jaibatrik** [comment] 2018-06-18 14:12
This was how the library was designed. Can someone please elucidate the problem in having the subscriber getting called twice? What exactly is the problem with AuthGuard for example.

**Comment by bodinaren** [comment] 2018-06-18 17:58
The problem is that you can let the AuthGuard wait for the result of an Observable, but when the Observable immediately returns `null` it'll immediately evaluate as falsy meaning the route won't get activated. Having the ReplaySubject would make it wait for the first update of the value which I think makes perfect sense. The `null` you use now is basically just a "random" placeholder which serves no purpose.

I think you will want to add some more handling which actually returns `null` when the user is not logged in though, as suggested in #52.

**Comment by jaibatrik** [comment] 2018-06-23 06:52
Makes sense. Do you think #85 should be enough?

**Comment by bodinaren** [comment] 2018-06-23 07:05
I don't like this. And in the case of the AuthGuard it's also not enough as it must return something at some point, otherwise the AuthGuard will get stuck. That's why I suggested https://github.com/abacritt/angularx-social-login/issues/52 instead.

**Comment by jaibatrik** [comment] 2018-06-23 07:45
Hmm, #52 does not have a PR I think. @BoBoss74 forked it, but he did not send a PR, as I was a bit skeptical about the idea back then.

**Comment by dmariano001** [comment] 2018-08-02 15:56
Any news on this? I am having the same issue.

**Comment by DouglasForst** [comment] 2018-08-02 16:18
I gave up on this and switched to use [Google's javascript library](https://developers.google.com/identity/sign-in/web/reference) directly. It's working great and it manages their api access tokens so that was a big plus.

**Comment by nguyentrunghieu3010** [comment] 2018-09-13 09:03
Your setting is not correctly in Developer FaceBook. And, I resolved this issue.
Test On Your Local
**- https://developers.facebook.com/apps/xxxxxxxxxxx/settings/basic/
- App Domains must be Empty
- Privacy Policy URL must be Empty
- Status: In Development
- Site URL: http://localhost:4200/**

**Comment by jaibatrik** [comment] 2018-11-25 05:58
Merged the change from `BehaviorSubject` to `ReplaySubject` and published to npm.

**Closed by jaibatrik** 2018-11-25 05:58 UTC

**Comment by silviodeligios** [comment] 2018-12-17 18:42
This fix is not working... now if you are not logged the user dispatch the null value!!

**Comment by jaibatrik** [comment] 2019-01-30 15:44
@silviodeligios I think #154 talks about this.
