### ISSUE TITLE
ERROR in Failed to find exported name of node

### ISSUE THREAD

**Issue by romelgomez** [abacritt/angularx-social-login#249] opened 2020-02-12 20:50 UTC
When I started a migration of an angular app 8 to 9 following things to-do, this error raise:

https://update.angular.io/#8.0:9.0

```
ERROR in Failed to find exported name of node (CommonModule = /** @class */ (function () {
    function CommonModule() {
    }
    CommonModule = __decorate([
        NgModule({
            declarations: [COMMON_DIRECTIVES, COMMON_PIPES],
            exports: [COMMON_DIRECTIVES, COMMON_PIPES],
            providers: [
                { provide: NgLocalization, useClass: NgLocaleLocalization },
            ],
        })
    ], CommonModule);
    return CommonModule;
}())) in '/home/dev/workpace/<project_name>/node_modules/angularx-social-login/angularx-social-login.es5.js'.
```

**Comment by LeParadoxHD** [comment] 2020-02-15 13:53
The problem is in Ivy, CommonModule is not longer necessary.

**Comment by jaibatrik** [comment] 2020-04-25 08:58
Added Angular 9 support recently. Closing this. Check usage in the app section of the repository.

**Closed by jaibatrik** 2020-04-25 08:58 UTC
