### ISSUE TITLE
 FB.login() called before FB.init(). 

### ISSUE THREAD

**Issue by shriramsalunkheprisanas** [abacritt/angularx-social-login#93] opened 2018-05-25 09:18 UTC
i'm getting 
FB.login() called before FB.init().  error on facebook button click

**Comment by jaibatrik** [comment] 2018-06-05 14:40
do you have a live sample somewhere that we can check?

**Comment by bodinaren** [comment] 2018-06-15 12:37
I've also experienced this. You can easily reproduce this in the demo page.

The error happens here: https://github.com/abacritt/angularx-social-login/blob/master/src/lib/src/providers/facebook-login-provider.ts#L54

The problem is that if you're too fast to call `authService.signIn()` the Facebook SDK is not loaded yet, so you get `ReferenceError: FB is not defined`.

I've submitted the PR above which will fix this.

**Comment by bodinaren** [comment] 2018-07-12 07:49
Fixed in the next version by PR #101

**Closed by bodinaren** 2018-07-12 07:49 UTC

**Comment by BruneXX** [comment] 2018-12-18 15:23
Hi Guys, I'm facing this issue? the way to deal with that is using **readState** this way?

`authService.readyState.subscribe((readyProviders) => {`

Is any other thing that I need to consider?

**Comment by bodinaren** [comment] 2018-12-18 16:54
You shouldn't need to if you have a version including this PR, it should already be handled internally.

The readyState is just for your convenience in case you want your interface to react accordingly (e.g. disable the Facebook button until it's ready), but doing this shouldn't be necessary.

**Comment by xjose97x** [comment] 2019-04-10 19:02
I'm still experiencing this.
