### ISSUE TITLE
Not working with Ivy

### ISSUE THREAD

**Issue by suwigyarathore** [abacritt/angularx-social-login#186] opened 2019-06-11 15:33 UTC
Trying to update my project to use ivy but this package is breaking the build 

```
ERROR in Failed to find exported name of node (CommonModule = /** @class */ (function () {
    function CommonModule() {
    }
    CommonModule.decorators = [
        { type: NgModule, args: [{
                    declarations: [COMMON_DIRECTIVES, COMMON_PIPES],
                    exports: [COMMON_DIRECTIVES, COMMON_PIPES],
                    providers: [
                        { provide: NgLocalization, useClass: NgLocaleLocalization },
                    ],
                },] }
    ];
    /** @nocollapse */
    CommonModule.ctorParameters = function () { return []; };
    return CommonModule;
}()))

```

**Comment by zepekenio** [comment] 2019-06-18 10:05
same for me

**Comment by GarrettCulos** [comment] 2019-07-11 19:59
Any movement on this? same issue here.

**Comment by keserwan** [comment] 2019-07-31 07:17
same here.
any progress?

**Comment by elementalPRESS** [comment] 2019-08-14 06:34
are there any news?

**Comment by aershov24** [comment] 2019-09-05 02:41
Same. Failing with **enableIvy** option. 

**ERROR in Value at position 0 in the NgModule.imports of SocialLoginModule is not a reference: [object Object]**

**Comment by zawars** [comment] 2019-09-06 10:28
@aershov24 Any solution so far?
i am facing the same issue.

**Comment by nadeemse** [comment] 2019-09-08 05:25
Same. Failing with enable Ivy option.

ERROR in Value at position 0 in the NgModule.imports of SocialLoginModule is not a reference: [object Object]

Any update on this ?

**Comment by keserwan** [comment] 2019-09-20 08:06
any progress? or any similar package for ivy?

**Comment by elementalPRESS** [comment] 2019-10-13 13:09
unfortunately, even with the new version 2.1.1 Ivy is not working :-(

**Comment by jaibatrik** [comment] 2019-10-13 16:41
I'll look into this when I get some time.

**Comment by elementalPRESS** [comment] 2019-10-15 07:06
> I'll look into this when I get some time.

This would be really great, because (I guess not just me) are going to prepare our apps for the next major release of Angular :-)

**Comment by ALEXOTANO** [comment] 2019-10-21 02:31
Same case here. 😐, any news? need more data ?

**Comment by somcoder** [comment] 2019-10-26 12:25
Reproduced this, and I can confirm that the issue exists. What's really interesting about this is the fact that this issue is caused by the `CommonModule` in `SocialLoginModule`'s imports, that does nothing (AFAIK) but to break everything!
Will submit a PR on this. ☺️

**Comment by ALEXOTANO** [comment] 2019-10-26 17:01
> Reproduced this, and I can confirm that the issue exists. What's really interesting about this is the fact that this issue is caused by the `CommonModule` in `SocialLoginModule`'s imports, that does nothing (AFAIK) but to break everything!
> Will submit a PR on this. ☺️

I can confirm that if you use `ng-packagr` as ( I think ) you suggested in other issue, solves the problem, I haven't PR beacause I didn't fully tested. (deploy to https server).

**Comment by somcoder** [comment] 2019-10-26 18:05
@ALEXOTANO That wasn't me, but from now on I'm suggesting `ng-packagr`. 😄
I checked with `ng-packagr`, and it works. I think so much overhead could've been removed just by using `ng-packagr`.

**Comment by ALEXOTANO** [comment] 2019-10-26 20:16
> @ALEXOTANO That wasn't me, but from now on I'm suggesting `ng-packagr`. 😄

An impostor!😆, sorry kind of dizzy with the back and forth with the IVY compiler. 

> I checked with `ng-packagr`, and it works. I think so much overhead could've been removed just by using `ng-packagr`.

Great! Yes, I've been able to solve that same problem with a couple of libraries just by using `ng-packagr`. Are you PRing it now ? did you test it in production?

**Comment by somcoder** [comment] 2019-10-27 08:12
@ALEXOTANO Yeah, I tested it with a project that I'm working on, and it works.
About the PR, the changes are higher, 32 so far, without even removing what needs to be removed.
Will wait for @jaibatrik to confirm on this, and then I will PR.

**Comment by ALEXOTANO** [comment] 2019-10-27 22:57
I know by first hand that the changes needed to be done won't take long but as you said its a major change (compiler), hope @jaibatrik  can approve on this soon. I want to test IVY since vesion 9 will be a default and we're behind the wave.

**Comment by omahjoub** [comment] 2019-11-10 08:35
Hi, Is there any plan to fix this?

**Comment by manchuwook** [comment] 2019-11-15 03:13
Even with AOT fix, getting this:
```
ERROR in Failed to compile entry-point angularx-social-login due to compilation errors:
node_modules/angularx-social-login/angularx-social-login.js(8050,26): error TS-991010: Value at position 0 in the NgModule.imports of SocialLoginModule is not a reference: [object Object]
```

**Comment by jaibatrik** [comment] 2019-11-23 19:24
#229 addresses this. I merged it and published it in npm. C2.2.0 should support Ivy according to the submitter of the PR.

**Closed by jaibatrik** 2019-11-23 19:24 UTC
Labels: help wanted
