### ISSUE TITLE
(SystemJS) XHR error (403 Forbidden) loading http://localhost:64921/node_modules/rxjs

### ISSUE THREAD

**Issue by AChandel01071994** [abacritt/angularx-social-login#11] opened 2017-09-26 07:18 UTC
I am using **systemjs.confg.js** to load the libraries.
To import **angular4-social-login** i have done this-

**'angular4-social-login': 'npm:angular4-social-login/angular4-social-login.umd.js',**

Now It is showing this error in **angular4-social-login.umd.js**

_(SystemJS) XHR error (403 Forbidden) loading http://localhost:64921/node_modules/rxjs_ 

I am using rxjs already and it is working fine.

Please Help asap.

**Comment by yoboka** [comment] 2018-01-20 11:57
I have the same problem.

Quickfix: Replace "rxjs" to "rxjs/rx" in "angular4-social-login.umd.js" within the node_modules folder.

But whenever you reinstall the modules, you will get the same error :(

**Comment by yoboka** [comment] 2018-01-21 10:13
Well, i think the issue was fixed by the latest update. Thank you! I don't see any RxJs dependency anymore, so the error does not occure anymore

**Comment by jaibatrik** [comment] 2018-01-23 07:43
Probably got fixed with new rollup or something. Closing for now, reopen if the issue is seen again.

**Closed by jaibatrik** 2018-01-23 07:43 UTC
Labels: help wanted
