### ISSUE TITLE
Google Login Not Working Anymore because the library is about to be depricated

### ISSUE THREAD

**Issue by sehcode** [abacritt/angularx-social-login#509] opened 2022-05-31 07:09 UTC
{error: 'idpiframe_initialization_failed', details: 'You have created a new client application that uses libraries for user authentication or authorization that will soon be deprecated. New clients must use the new libraries instead; existing clients must also migrate before these libraries are deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information.'}

**Comment by pradosh05** [comment] 2022-06-06 17:07
I am getting the same issue, Can you please help us..

**Comment by cacalo** [comment] 2022-06-10 17:11
Mine is working correctly. I just used google to login to my site (which uses this package).

**Comment by jviaches** [comment] 2022-06-10 18:56
same hete as @cacalo . Still show a warning about deprication but allow to succesfully login with google provider

**Comment by Heatmanofurioso** [comment] 2022-06-13 08:23
This issue is a duplicate of #504 
I'm closing this one, since the other one is the oldest, and so we can discuss this in a single thread.

It is also being addressed in https://github.com/abacritt/angularx-social-login/pull/507 for those interested

**Closed by Heatmanofurioso** 2022-06-13 08:23 UTC
