### ISSUE TITLE
how to add dynamic facebook and google PROVIDER_ID?

### ISSUE THREAD

**Issue by harleenarora** [abacritt/angularx-social-login#50] opened 2018-01-23 04:28 UTC
Hi, Please tell me how to add dynamic add Facebook and google PROVIDER_ID?

**Comment by jaibatrik** [comment] 2018-01-23 07:18
What is your use case? Please be elaborate.

**Comment by harleenarora** [comment] 2018-01-23 08:55
I am write a step, please check it and tell me:-
app.module.ts:- 

`import { SocialLoginModule, AuthServiceConfig } from "angularx-social-login";
import { GoogleLoginProvider, FacebookLoginProvider } from "angularx-social-login";

let config = new AuthServiceConfig([
 {
  id: GoogleLoginProvider.PROVIDER_ID,
  provider: new GoogleLoginProvider("Google-OAuth-Client-Id")
 },
 {
  id: FacebookLoginProvider.PROVIDER_ID,
  provider: new FacebookLoginProvider('Facebook-App-Client-Id')
 }
]);

export function provideConfig() {
  return config;
}

@NgModule({
  declarations: [
   AppComponent
  ],
  imports: [
    SocialLoginModule
  ],
  providers: [
  {
    provide: AuthServiceConfig,
    useFactory: provideConfig
  }
 ],
  entryComponents: [],
  bootstrap: []
})
export class AppModule { }`

main.component.ts:- 
`import { AuthService,SocialUser } from "angularx-social-login";
import { FacebookLoginProvider, GoogleLoginProvider } from "angularx-social-login";


export class MainComponent implements OnInit {

   private user: SocialUser;
   private loggedIn: boolean;

   constructor(private authService: AuthService) { 

      // this.authService(this.config);
   }

   signInWithGoogle(): void {
    this.authService.signIn(GoogleLoginProvider.PROVIDER_ID);
   }

   signInWithFB(): void {
    this.authService.signIn(FacebookLoginProvider.PROVIDER_ID);
   }

   signOut(): void {
    this.authService.signOut();
   }

   ngOnInit() {
      this.authService.authState.subscribe((user) => {
         this.user = user;
         this.loggedIn = (user != null);
      });

      console.log(this.user);
   }
`
Please tell me how to pass the Config from main.ts file.

**Comment by jaibatrik** [comment] 2018-02-24 06:05
Duplicate of #59

**Closed by jaibatrik** 2018-02-24 06:05 UTC
